name: Rust

on:
  pull_request:
  push:
    branches:
      - develop

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@nightly
      - name: Cache cargo artifacts
        uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build
      - name: Test
        run: cargo test

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy
      - name: Cache cargo artifacts
        uses: Swatinem/rust-cache@v2
      - name: Run clippy
        run: cargo clippy --all-targets -- -D warnings

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - name: Run rustfmt
        run: cargo fmt --all --check
